# SPDX-License-Identifier: GPL-2.0-or-later
"""Build digihealth's .elemod for the device your stock file is for.

    python build.py --stock Digitakt_OS1.53.syx [--out DIR]          (or 1.54)
    python build.py --stock Digitone_and_Digitone_Keys_OS1.43.syx [--out DIR]

On the Digitone mk1 it is SYSTEM INFO alone (dn1/mod.json), which the SDK
builds as it is: FAST AUDIO, below, is the Digitakt mk1's.

FAST AUDIO needs parts that depend on the stock code it copies: the block's
checks, its fix-ups (the copy's references to itself, pointed at the copy)
and the render's call-site stubs. This script works them out from your
stock file, then hands them to elekloader's SDK (elekloader.sdk.build),
which builds the mod as `python -m elekloader.sdk.build` would.

elekloader must be importable (pip install it, or set PYTHONPATH to its
folder). Like the SDK, it needs the device's cross toolchain: for the
Digitakt mk1, m68k-linux-gnu-as, -gcc and -ld (ELEKLOADER_CROSS for another
prefix).
"""
import argparse
import json
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


class PlanError(Exception):
    pass


def plan_block(cf, image, lo, hi, dst, dst_end, base):
    """-> (length, fix-ups [(SRAM address, value, image address)]). Refuses a
    block that could not run from the SRAM: an instruction the part does not
    have, a PC-relative operand or a branch that leaves the block."""
    n = (hi - lo + 3) // 4 * 4
    if dst + n > dst_end:
        raise PlanError('the block does not fit the SRAM: it would end at 0x%08x' % (dst + n))
    read = cf.reader(image, base)
    fixups, a, prev = [], lo, None
    while a < hi:
        ins = cf.decode(read(a), a)
        bad = ins.flags & (cf.ILLEGAL | cf.LINEF | cf.FPU)
        padding = (bad and ins.length == 2 and image[a - base:a - base + 2] == b'\0\0'
                   and prev is not None
                   and prev.flow in (cf.F_RTS, cf.F_RTE, cf.F_BRA, cf.F_JMP))
        if bad and not padding:
            raise PlanError('0x%08x %s cannot run from SRAM' % (a, ins.op))
        if ins.flags & cf.PCREL:
            d16 = struct.unpack('>h', image[a - base + 2:a - base + 4])[0]
            if not lo <= a + 2 + d16 < hi:
                raise PlanError('0x%08x %s: PC-relative out of the block' % (a, ins.op))
        if isinstance(ins.target, int) and ins.flow != cf.F_JSR and not lo <= ins.target < hi:
            raise PlanError('0x%08x branches out of the block, to 0x%08x' % (a, ins.target))
        for off in range(2, ins.length - 3, 2):
            v = struct.unpack('>I', image[a - base + off:a - base + off + 4])[0]
            if lo <= v < hi:
                fixups.append((dst + (a - lo) + off, dst + (v - lo), a + off))
        prev = ins
        a += ins.length
    if a != hi:
        raise PlanError('the block does not decode to 0x%08x' % hi)
    return n, fixups


def stubs_source(entries, lo, dst):
    """The call-site stubs: r_<addr> goes through rp_<addr>, which reloc_on and
    reloc_off point at the SRAM copy or the image's code; stub_tab holds
    (&pointer, image entry, SRAM entry) per entry."""
    lines = ['| FAST AUDIO call-site stubs (generated by build.py)',
             '        .section .run, "ax"',
             '        .globl  stub_tab, stub_count',
             '        .equ    stub_count, %d' % len(entries)]
    for e in entries:
        lines += ['        .globl  r_%08x, rp_%08x' % (e, e),
                  'r_%08x:  move.l  rp_%08x, -(%%sp)' % (e, e), '        rts']
    lines += ['        .balign 4']
    for e in entries:
        lines += ['rp_%08x: .long   0x%08x' % (e, e)]
    lines += ['stub_tab:']
    for e in entries:
        lines += ['        .long   rp_%08x, 0x%08x, 0x%08x' % (e, e, dst + (e - lo))]
    return '\n'.join(lines) + '\n'


def generate(cf, mod, image, base, work):
    """-> the SDK's `extra`: the stubs source, the call sites, and the entries
    for fa_copies and fa_fixups (each fix-up claims the 4 image bytes it
    rewrites in the copy, so no other mod may patch them)."""
    fa = mod['fast_audio']
    lo, hi = int(fa['block'][0], 16), int(fa['block'][1], 16)
    dst, dend = int(fa['sram'][0], 16), int(fa['sram'][1], 16)
    n, fixups = plan_block(cf, image, lo, hi, dst, dend, base)
    entries = sorted({int(t, 16) for _s, _o, t in fa['call_sites']})
    path = os.path.join(work, 'fa_stubs.s')
    with open(path, 'w') as fh:
        fh.write(stubs_source(entries, lo, dst))
    sites = [{'addr': s, 'stock': op + '%08x' % int(t, 16), 'op': 'keep2',
              'target': 'r_%08x' % int(t, 16)} for s, op, t in fa['call_sites']]
    contrib = [{'to': 'fa_copies', 'order': 0,
                'data': struct.pack('>IIII', lo, dst, n, 0).hex(), 'relocs': [], 'claims': []}]
    for sram, v, img in fixups:
        contrib.append({'to': 'fa_fixups', 'order': 0,
                        'data': struct.pack('>II', sram, v).hex(), 'relocs': [],
                        'claims': [['0x%08x' % img, '0x%08x' % (img + 4)]]})
    return {'sources': [path], 'sites': sites, 'contribute': contrib}, len(fixups), len(entries)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--stock', default=os.environ.get('ELEKLOADER_STOCK'),
                    help='the stock OS file (default: $ELEKLOADER_STOCK)')
    ap.add_argument('--out', help='where to write the .elemod (default: out/)')
    a = ap.parse_args(argv)
    if not a.stock:
        ap.error('--stock is required (or set ELEKLOADER_STOCK)')
    try:
        from elekloader import devices, syx
        from elekloader.isa import coldfire as cf
        from elekloader.sdk import build as sdk
    except ImportError:
        print('BUILD FAILED: elekloader is not importable (pip install it, or set PYTHONPATH '
              'to its folder)')
        return 1
    with open(os.path.join(HERE, 'mod.json')) as fh:
        mod = json.load(fh)
    out = a.out or os.path.join(HERE, 'out')
    work = os.path.join(out, mod['id'] + '.work')
    os.makedirs(work, exist_ok=True)
    try:
        stock = syx.Syx.load(a.stock)
        dev, rel = devices.identify(stock.sha256)
        if dev.key == 'digitone-mk1':
            path, m = sdk.build(os.path.join(HERE, 'dn1'), a.stock, out)
            print('BUILT %s' % path)
            print('  %s: .run %d, .bss %d bytes; %d sites, %d relocations; SYSTEM INFO only'
                  % (m.label(), m.size('.run'), m.size('.bss'), len(m.sites), len(m.relocs)))
            return 0
        mod, _ported = sdk.for_release(mod, dev, rel)    # this OS's "ports" entry, if any
        image = stock.section(dev.main_section)
        extra, nfix, nstub = generate(cf, mod, image, dev.main_load, work)
        path, m = sdk.build(HERE, a.stock, out, extra)
    except (PlanError, sdk.BuildError, devices.UnknownFirmware, OSError, KeyError,
            ValueError) as e:
        print('BUILD FAILED: %s' % e)
        return 1
    print('BUILT %s' % path)
    print('  %s: .run %d, .fast %d, .bss %d bytes; %d sites, %d relocations; FAST AUDIO: '
          '%d fix-ups, %d call-site stubs' % (m.label(), m.size('.run'), m.size('.fast'),
                                              m.size('.bss'), len(m.sites), len(m.relocs),
                                              nfix, nstub))
    return 0


if __name__ == '__main__':
    sys.exit(main())
